# Debug Configuration - Fast Startup for Testing
# این کانفیگ برای debugging و تست سریع طراحی شده

model:
  # مدل کوچک‌تر برای compile سریع‌تر
  text_encoder:
    dim: 256      # کاهش از 512
    n_layer: 4    # کاهش از 8
    n_head: 4     # کاهش از 8
  
  audio_encoder:
    dim: 384      # کاهش از 768
    n_layer: 4    # کاهش از 8
    n_head: 6     # کاهش از 12
  
  decoder:
    dim: 768      # کاهش از 1536
    n_layer: 8    # کاهش از 16
    n_head: 12    # کاهش از 24
  
  max_attention_sequence_length: 256  # کاهش از 512

training:
  epochs: 1
  learning_rate: 5e-5
  batch_size: 8           # کاهش batch size
  gradient_accumulation_steps: 1
  
  # Loss weights (ساده‌تر)
  mel_loss_weight: 1.0
  kl_loss_weight: 0.1     # کاهش
  
  # Scheduler ساده‌تر
  scheduler: "linear"     # بجای noam
  
  # GPU settings
  multi_gpu: false        # تک GPU برای debugging
  
  # Checkpointing
  save_step: 50
  val_step: 25
  log_step: 5
  
  # Optimization
  weight_decay: 1e-6
  gradient_clip_norm: 0.5
  
  # Memory optimization
  enable_memory_cleanup: true
  use_mixed_precision: false  # غیرفعال برای debugging

data:
  batch_size: 8
  num_workers: 4          # کاهش workers
  max_mel_frames: 400     # کاهش از default
  
audio:
  sample_rate: 22050
  n_fft: 1024
  hop_length: 256
  win_length: 1024
  n_mels: 80

vocoder:
  type: "griffin_lim"     # ساده‌ترین vocoder

loss:
  # Simple loss configuration
  use_adaptive_loss_weights: false
  use_label_smoothing: false
  use_huber_loss: false