model:
  # Architecture
  text_encoder_dim: 512      # Text encoder dimension
  decoder_dim: 1024          # Decoder dimension
  text_encoder_layers: 6     # Number of transformer layers
  
  # Audio settings
  sample_rate: 22050         # Audio sample rate
  n_mels: 80                 # Mel spectrogram channels
  
  # Voice cloning
  use_voice_conditioning: true
  speaker_embedding_dim: 256
  
  # Languages
  languages: [en, es, fr, de, it, pt, pl, tr, ru, nl, cs, ar, zh, ja, hu, ko]
  
training:
  epochs: 1000
  learning_rate: 1e-4
  optimizer: adamw
  scheduler: noam
  
  # Improved loss weights for better stability
  mel_loss_weight: 35.0        # Reduced from 45.0 for better balance
  kl_loss_weight: 1.0
  
  # Training stability improvements  
  use_adaptive_loss_weights: true      # Enable adaptive loss weight scaling
  loss_smoothing_factor: 0.1           # Exponential smoothing factor
  max_loss_spike_threshold: 2.0        # Maximum allowed loss spike multiplier
  gradient_norm_threshold: 5.0         # Threshold for gradient norm monitoring
  
  # Enhanced loss function options
  use_label_smoothing: true            # Enable label smoothing for regularization
  mel_label_smoothing: 0.05           # Label smoothing for mel loss
  stop_label_smoothing: 0.1           # Label smoothing for stop token loss
  use_huber_loss: true                # Use Huber loss for mel loss stability
  huber_delta: 1.0                    # Delta parameter for Huber loss
  stop_token_positive_weight: 5.0     # Weight for positive stop tokens
  
  # Learning rate improvements
  use_warmup_cosine_schedule: true     # Use cosine annealing with warmup
  min_learning_rate: 1e-6             # Minimum learning rate
  
  # Early stopping improvements
  early_stopping_patience: 25          # Increased patience for stability
  early_stopping_min_delta: 0.0005    # Smaller delta for fine-grained stopping
  
  # Checkpointing
  save_step: 25000
  val_step: 5000
  checkpoint_dir: "./checkpoints"

data:
  dataset_path: "./data/ljspeech"
  dataset_name: "ljspeech"
  language: "en"
  
  # Audio processing
  sample_rate: 22050
  normalize_audio: true
  trim_silence: true
  
  # Text processing
  text_cleaners: ["english_cleaners"]
  add_blank: true
  
  # Training splits
  train_split: 0.9
  val_split: 0.1
  batch_size: 56               # Increased for better GPU utilization
  num_workers: 18              # Increased for better CPU utilization
  
  # GPU optimization settings
  prefetch_buffer_size: 8      # Increased for better GPU utilization
  shuffle_buffer_multiplier: 20
  enable_xla: true             # Enable XLA compilation
  mixed_precision: true        # Enable mixed precision
  pin_memory: true             # Pin memory for faster GPU transfer
  
  # Dataset preprocessing control
  preprocessing_mode: auto     # "auto", "precompute", "runtime"