model:
  text_encoder_dim: 512
  decoder_dim: 1024
  text_encoder_layers: 6
  decoder_layers: 6
  encoder_attention_heads: 8
  decoder_attention_heads: 8
  sample_rate: 22050
  n_mels: 80
  hop_length: 256
  win_length: 1024
  fmin: 0
  fmax: 8000
  use_voice_conditioning: true
  speaker_embedding_dim: 256
  languages:
  - en
  - es
  - fr
  - de
  - it
  - pt
  - pl
  - tr
  - ru
  - nl
  multi_language: true
training:
  epochs: 500
  learning_rate: 8.0e-05
  warmup_steps: 1500
  weight_decay: 5.0e-07
  gradient_clip_norm: 0.8
  gradient_accumulation_steps: 2
  optimizer: adamw
  beta1: 0.9
  beta2: 0.999
  eps: 1.0e-08
  mel_loss_weight: 22.0
  kl_loss_weight: 1.8
  stop_loss_weight: 1.5
  attention_loss_weight: 0.3
  duration_loss_weight: 0.8
  use_adaptive_loss_weights: true
  loss_smoothing_factor: 0.08
  max_loss_spike_threshold: 1.3
  gradient_norm_threshold: 2.5
  use_label_smoothing: true
  mel_label_smoothing: 0.025
  stop_label_smoothing: 0.06
  use_huber_loss: true
  huber_delta: 0.6
  stop_token_positive_weight: 4.0
  scheduler: cosine_with_restarts
  use_warmup_cosine_schedule: true
  min_learning_rate: 1.0e-07
  cosine_restarts: true
  restart_period: 8000
  restart_mult: 0.8
  early_stopping_patience: 40
  early_stopping_min_delta: 5.0e-05
  early_stopping_restore_best_weights: true
  save_step: 2000
  val_step: 1000
  log_step: 50
  checkpoint_dir: ./checkpoints
data:
  dataset_path: ./data/ljspeech
  dataset_name: ljspeech
  language: en
  batch_size: 48
  num_workers: 12
  prefetch_buffer_size: 10
  shuffle_buffer_multiplier: 15
  sample_rate: 22050
  n_mels: 80
  normalize_audio: true
  trim_silence: true
  text_cleaners:
  - english_cleaners
  add_blank: true
  train_split: 0.9
  val_split: 0.1
  max_mel_frames: 800
  max_text_length: 180
  pad_to_multiple: 8
  preprocessing_mode: precompute
  enable_memory_mapping: true
  cache_verification: true
  pin_memory: true
  prefetch_to_gpu: true
  enable_xla: true
  mixed_precision: true
  optimize_cpu_gpu_overlap: true
  enhanced_gpu_prefetch: true
  use_tf_native_loading: true
