data:
  add_blank: true
  batch_size: 32
  cache_verification: true
  dataset_name: ljspeech
  dataset_path: ./data/test
  enable_memory_mapping: true
  enable_tensorrt: false
  enable_xla: true
  eval_subset_fraction: 1.0
  language: en
  max_mel_frames: 512
  metadata_eval_file: ../dataset/dataset_eval/metadata_eval.csv
  metadata_train_file: ../dataset/dataset_train/metadata_train.csv
  mixed_precision: true
  normalize_audio: true
  num_workers: 8
  persistent_workers: true
  pin_memory: true
  prefetch_buffer_size: 6
  prefetch_to_gpu: true
  preprocessing_mode: auto
  sample_rate: 22050
  shuffle_buffer_multiplier: 15
  subset_seed: 42
  text_cleaners:
  - english_cleaners
  train_split: 0.9
  train_subset_fraction: 1.0
  trim_silence: true
  val_split: 0.1
  wavs_eval_dir: ../dataset/dataset_train/wavs
  wavs_train_dir: ../dataset/dataset_train/wavs
model:
  audio_encoder_dim: 512
  audio_encoder_heads: 8
  audio_encoder_layers: 6
  decoder_dim: 1024
  decoder_heads: 16
  decoder_layers: 12
  hop_length: 256
  languages:
  - en
  - es
  - fr
  - de
  - it
  - pt
  - pl
  - tr
  - ru
  - nl
  - cs
  - ar
  - zh
  - ja
  - hu
  - ko
  max_text_length: 500
  n_fft: 1024
  n_mels: 80
  sample_rate: 22050
  speaker_embedding_dim: 256
  text_encoder_dim: 512
  text_encoder_heads: 8
  text_encoder_layers: 6
  text_vocab_size: 256256
  tokenizer_model: facebook/nllb-200-distilled-600M
  tokenizer_type: nllb
  use_voice_conditioning: true
  win_length: 1024
training:
  beta1: 0.9
  beta2: 0.999
  checkpoint_dir: ./checkpoints
  duration_loss_weight: 1.0
  epochs: 100
  eps: 1.0e-08
  gradient_accumulation_steps: 4
  gradient_clip_norm: 1.0
  kl_loss_weight: 1.0
  learning_rate: 0.0001
  log_step: 100
  mel_loss_weight: 45.0
  multi_gpu: false
  optimizer: adamw
  save_step: 1000
  scheduler: noam
  scheduler_params: {}
  use_wandb: false
  val_step: 500
  visible_gpus: null
  wandb_project: myxtts
  warmup_steps: 4000
  weight_decay: 1.0e-06
