#!/bin/bash
# Intelligent GPU Pipeline System - Usage Examples
# This script demonstrates various usage patterns for the new GPU pipeline system

echo "================================================"
echo "Intelligent GPU Pipeline System - Examples"
echo "================================================"
echo ""

# Example 1: Single-GPU Buffered Mode (Default)
echo "Example 1: Single-GPU Buffered Mode with default buffer (50)"
echo "-----------------------------------------------------"
echo "python train_main.py \\"
echo "    --train-data ./dataset/train \\"
echo "    --val-data ./dataset/val \\"
echo "    --batch-size 32 \\"
echo "    --epochs 100"
echo ""
echo "Expected: Uses smart prefetching with buffer size of 50"
echo ""

# Example 2: Single-GPU Buffered Mode with custom buffer
echo "Example 2: Single-GPU Buffered Mode with large buffer (100)"
echo "-----------------------------------------------------"
echo "python train_main.py \\"
echo "    --train-data ./dataset/train \\"
echo "    --val-data ./dataset/val \\"
echo "    --buffer-size 100 \\"
echo "    --batch-size 64 \\"
echo "    --num-workers 16 \\"
echo "    --epochs 100"
echo ""
echo "Expected: Increased buffer size for better GPU utilization"
echo ""

# Example 3: Multi-GPU Mode
echo "Example 3: Multi-GPU Mode (GPU 0 for data, GPU 1 for model)"
echo "-----------------------------------------------------"
echo "python train_main.py \\"
echo "    --train-data ./dataset/train \\"
echo "    --val-data ./dataset/val \\"
echo "    --data-gpu 0 \\"
echo "    --model-gpu 1 \\"
echo "    --batch-size 64 \\"
echo "    --num-workers 16 \\"
echo "    --epochs 500"
echo ""
echo "Expected: Data processing on GPU:0, model training on GPU:1"
echo "Expected: Model starts after 2.0s delay"
echo ""

# Example 4: Multi-GPU Mode with custom settings
echo "Example 4: Multi-GPU Mode with custom delay and buffer"
echo "-----------------------------------------------------"
echo "python train_main.py \\"
echo "    --train-data ./dataset/train \\"
echo "    --val-data ./dataset/val \\"
echo "    --data-gpu 0 \\"
echo "    --model-gpu 1 \\"
echo "    --buffer-size 75 \\"
echo "    --model-start-delay 3.5 \\"
echo "    --batch-size 64 \\"
echo "    --epochs 500"
echo ""
echo "Expected: Extended delay for slower storage systems"
echo ""

# Example 5: Memory-constrained system
echo "Example 5: Memory-Constrained System"
echo "-----------------------------------------------------"
echo "python train_main.py \\"
echo "    --train-data ./dataset/train \\"
echo "    --val-data ./dataset/val \\"
echo "    --buffer-size 25 \\"
echo "    --batch-size 16 \\"
echo "    --grad-accum 4 \\"
echo "    --num-workers 4 \\"
echo "    --model-size small \\"
echo "    --epochs 100"
echo ""
echo "Expected: Reduced buffer to save memory"
echo ""

# Example 6: Production training with Multi-GPU
echo "Example 6: Production Training (Multi-GPU + Static Shapes)"
echo "-----------------------------------------------------"
echo "python train_main.py \\"
echo "    --train-data ./dataset/train \\"
echo "    --val-data ./dataset/val \\"
echo "    --data-gpu 0 \\"
echo "    --model-gpu 1 \\"
echo "    --buffer-size 100 \\"
echo "    --batch-size 64 \\"
echo "    --num-workers 16 \\"
echo "    --enable-static-shapes \\"
echo "    --optimization-level enhanced \\"
echo "    --epochs 500"
echo ""
echo "Expected: Maximum GPU utilization with all optimizations"
echo ""

# Example 7: Development/debugging with Single-GPU
echo "Example 7: Development/Debugging"
echo "-----------------------------------------------------"
echo "python train_main.py \\"
echo "    --train-data ./dataset/train \\"
echo "    --val-data ./dataset/val \\"
echo "    --buffer-size 30 \\"
echo "    --batch-size 8 \\"
echo "    --model-size tiny \\"
echo "    --epochs 10 \\"
echo "    --enable-eager-debug"
echo ""
echo "Expected: Fast iteration for debugging"
echo ""

echo "================================================"
echo "For more information, see:"
echo "  docs/INTELLIGENT_GPU_PIPELINE.md"
echo "================================================"
