# Compatibility Configuration for MyXTTS
# Maintains backward compatibility while providing upgrade path to neural vocoder

model:
  # Text encoder settings - Standard
  text_encoder_dim: 512
  text_encoder_layers: 6
  text_encoder_heads: 8
  text_vocab_size: 256256
  
  # Audio encoder settings - Standard
  audio_encoder_dim: 512
  audio_encoder_layers: 6
  audio_encoder_heads: 8
  
  # Decoder settings - Classic autoregressive
  decoder_strategy: "autoregressive"
  decoder_dim: 1024
  decoder_layers: 12
  decoder_heads: 16
  
  # HiFi-GAN vocoder (always used)
  
  # Mel spectrogram settings
  n_mels: 80
  n_fft: 1024
  hop_length: 256
  win_length: 1024
  sample_rate: 22050
  
  # Voice conditioning - Standard
  speaker_embedding_dim: 256
  use_voice_conditioning: true
  voice_conditioning_layers: 2
  voice_similarity_threshold: 0.75
  enable_voice_adaptation: true
  voice_encoder_dropout: 0.1
  
  # Advanced features
  enable_gradient_checkpointing: false
  max_attention_sequence_length: 512
  use_memory_efficient_attention: true

training:
  # Standard single-stage training
  use_two_stage_training: false
  
  # Training settings
  epochs: 100
  learning_rate: 1e-4
  checkpoint_path: "checkpoints/compat"
  
  # General training settings
  batch_size: 32
  num_workers: 8
  enable_mixed_precision: false
  gradient_clip_norm: 1.0
  weight_decay: 0.01
  
  # Loss weights - Classic XTTS
  mel_loss_weight: 1.0
  stop_loss_weight: 0.5

data:
  dataset_path: ""
  dataset_name: "ljspeech"
  sample_rate: 22050
  trim_silence: true
  normalize_audio: true
  language: "en"
  
  # Standard batching
  batch_size: 32
  num_workers: 8
  prefetch_buffer_size: 8
  shuffle_buffer_multiplier: 20

# Upgrade path for better quality:
# 1. Train with this configuration
# 2. Set use_two_stage_training to true
# 3. Retrain with two-stage approach for best quality

# Usage notes:
# This configuration ensures compatibility with existing workflows
# Provides baseline quality comparable to original XTTS
# Can be gradually upgraded to use new features
# Suitable for environments where stability is paramount