# GPU Utilization Optimized Configuration for MyXTTS
# =====================================================
# 
# این configuration برای رفع مسئله GPU utilization که بین 40% و 2% نوسان می‌کند طراحی شده است.
# 
# ویژگی‌های کلیدی:
# - Async data prefetching برای کاهش GPU idle time
# - Optimized DataLoader settings
# - Memory management بهینه‌شده
# - Real-time GPU monitoring
# - Enhanced batch processing
#
# استفاده:
# python3 train_main.py --config config_gpu_utilization_optimized.yaml --model-size tiny
#
# Generated automatically by gpu_utilization_config.py
# Date: 1758848738.235649

data:
  async_data_loading: true
  cache_data: true
  cache_verification: true
  drop_last: true
  enable_audio_normalization: true
  enable_memory_mapping: true
  enable_phonemes: true
  enable_text_normalization: true
  hop_length: 256
  max_audio_length: 11.0
  max_text_length: 200
  min_audio_length: 0.5
  min_text_length: 10
  multiprocessing_context: spawn
  n_fft: 1024
  n_mels: 80
  num_workers: 8
  persistent_workers: true
  phoneme_language: en
  pin_memory: true
  prefetch_buffer_size: 24
  prefetch_factor: 4
  preload_data: true
  sample_rate: 22050
  shuffle_buffer_multiplier: 36
  win_length: 1024
gpu_optimization:
  cleanup_interval: 100
  enable_async_prefetch: true
  enable_memory_defragmentation: true
  enable_memory_pool: true
  enable_performance_logging: true
  log_gpu_stats: true
  log_memory_stats: true
  log_timing_stats: true
  max_prefetch_batches: 8
  memory_pool_size: auto
  min_gpu_utilization_warning: 50.0
  monitoring_interval: 50
  target_gpu_utilization: 85.0
logging:
  level: INFO
  log_data_loading_time: true
  log_gpu_utilization: true
  log_memory_usage: true
  save_training_plots: true
model:
  architecture: transformer
  attention_implementation: flash_attention_2
  audio_encoder:
    dim: 512
    dropout: 0.1
    head_dim: 64
    heads: 8
    layers: 6
  decoder:
    dim: 768
    dropout: 0.1
    head_dim: 64
    heads: 12
    layers: 8
  enable_gradient_checkpointing: true
  mixed_precision: true
  model_type: xtts
  speaker_embedding:
    conditioning_layers: 3
    dim: 256
  text_encoder:
    dim: 256
    dropout: 0.1
    head_dim: 32
    heads: 8
    layers: 4
paths:
  cache_dir: ./cache_gpu_optimized
  checkpoint_dir: ./checkpoints_gpu_optimized
  log_dir: ./logs_gpu_optimized
training:
  batch_size: 16
  checkpoint_interval: 1000
  early_stopping_patience: 10
  enable_memory_efficient_attention: true
  epochs: 500
  feature_loss_weight: 1.0
  gradient_accumulation_steps: 2
  gradient_clip_norm: 1.0
  kl_loss_weight: 1.0
  label_smoothing_factor: 0.1
  learning_rate: 0.0001
  max_attention_sequence_length: 384
  max_memory_fraction: 0.75
  mel_loss_weight: 1.0
  scheduler: cosine_with_restarts
  use_adaptive_loss_weights: true
  use_label_smoothing: true
  validation_interval: 500
  warmup_steps: 1000
  weight_decay: 1.0e-06
